dias = int(input('Dias: '))
horas = int(input('Horas: '))
minutos = int(input('Minutos: '))
segundos = int(input('Segundos: '))
calculado = segundos + (minutos * 60) + (horas * 3600) + ((dias * 24) * 3600)

print('Convertidor a segundos')
print(f'Dígame un número de días: {dias}')
print(f'Dígame un número de horas: {horas}')
print(f'Dígame un número de minutos: {minutos}')
print(f'Dígame un número de segundos: {segundos}')
print(f'{dias} días, {horas} horas, {minutos} minutos y {segundos} segundos son {calculado} segundos')
