# Generated by Django 3.2.3 on 2021-06-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=200)),
                ('nodeName', models.CharField(max_length=200)),
                ('release', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('bootTime', models.DateTimeField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
                ('available', models.BigIntegerField()),
                ('used', models.BigIntegerField()),
                ('percentage', models.FloatField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.sistem')),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentBytesFromBoot', models.BigIntegerField()),
                ('receivedBytesFromBoot', models.BigIntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.sistem')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readBytesFromBoot', models.BigIntegerField()),
                ('writeBytesFromBoot', models.BigIntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.sistem')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalCores', models.BigIntegerField()),
                ('totalCores', models.BigIntegerField()),
                ('frequencyMax', models.FloatField()),
                ('frequencyMin', models.FloatField()),
                ('frequencyCurrent', models.FloatField()),
                ('cpuTotalUsage', models.FloatField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.sistem')),
            ],
        ),
    ]
